---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: "15"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### New features and improvements ###
  - Add pagination to scheduled tasks (#111) @crobibero
  - Implement deauth (#114) @Shadowghost
  - Sync Pause and Resume, enable analyzers (#112) @Shadowghost

  ### Bug Fixes ###
  - Send pause instead of stop on uncompleted playback to prevent scrobble (#117) @Shadowghost
  - Require success response before deserializing (#115) @crobibero
